### ISSUE TITLE
Add option to choose which field to use as event name for structured events

### ISSUE THREAD

**Issue by benjben** [snowplow-incubator/snowplow-indicative-relay#138]
At the moment, Indicative event name is retrieved from enriched event's `event_name` (see [this line](https://github.com/snowplow-incubator/snowplow-indicative-relay/blob/0.4.0/src/main/scala/com/snowplowanalytics/indicative/Transformer.scala#L74)). This field corresponds to the name of the event's schema (see [this line](https://github.com/snowplow/enrich/blob/master/modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala#L654)).

In case of structured events, the value of this field is always `"event"` (see [this line](https://github.com/snowplow/enrich/blob/master/modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/SchemaEnrichment.scala#L49) and [this line](https://github.com/snowplow/enrich/blob/master/modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/SchemaEnrichment.scala#L34)).

We should make it possible to specify in the configuration of the lambda which field to use as event name when the value is just `"event"` (e.g. `se_action` or `se_category`).

**Comment by colmsnowplow** [comment]
Honestly I would say that the best call is to always use `event_name` rather than choosing one or the other. `event` is the very old legacy field and will always be less useful. (for example all custom events will have `unstruct` for `event` but will have the actual event name for `event_name`. Confusingly though, some standard events will also have `unstruct` for `event`).

**Comment by benjben** [comment]
> event is the very old legacy field and will always be less useful.

Here we are not talking about `event` field but of the value of `event_name`, which is `"event"` for structured events. Event name `"event"` is not very useful.

**Comment by colmsnowplow** [comment]
Ohhhh... OK I understand - that makes sense
